SpecSelRepos/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SpecSelRepos.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class DownloadController : Controller
    {
        
        public FileResult SpecSel()
        {
            var fileName = $"SpeciesSelection.jar";
            var filepath = $"Download/{fileName}";
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);
            return File(fileBytes, "application/jar", fileName);
        }



        public FileResult ReadMe()
        {
            var fileName = $"ReadMe_2.1.txt";
            var filepath = $"Download/{fileName}";
            byte[] fileBytes = System.IO.File.ReadAllBytes(filepath);
            return File(fileBytes, "application/txt", fileName);
        }
    }
}

SpecSelRepos/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SpecSelRepos.Models;

namespace SpecSelRepos.Controllers
{

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Species Selection Repository About Page";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Species Selection Repository Contact Page";
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpecSelRepos/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>
    The Species Selection software is designed to select species from a set of data for monitoring of habit health.
    The algorithm is based upon papers X and Y. This website is designed to store results output by the species
    selection program along with details of the input dataset and settings used in the application.
</p>

SpecSelRepos/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    University of East Anglia<br />
    Norwich Research Park<br />
    Norwich<br />
    NR4 7TJ<br />
    UK<br />
    <abbr title="Phone">Phone:</abbr>
    +44 (0)1603 456161
</address>

<address>
    <strong>Enquiries:</strong> <a href="mailto:simon.butler@uea.ac.uk">simon.butler@uea.ac.uk</a><br />
    <strong>Support:</strong> <a href="mailto:taoyang.wu@uea.ac.uk">taoyang.wu@uea.ac.uk</a>
</address>

SpecSelRepos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-3">
        <h2>Species Selection</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
            <li>This webpage developed using <a href="https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1">Razor Pages Movie tutorial</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Papers</h2>
        <ul>
            <li><a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0097217">A niche-based framework to assess current monitoring of European forest birds and guide indicator species.</a></li>
            <li><a href="https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/j.2041-210X.2011.00173.x">An objective, niche-based approach to indicator species selection.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Download</h2>
        <ul>
            <li>@Html.ActionLink("Species Selection 2.0", "SpecSel", "Download")</li>
            <li>@Html.ActionLink("Readme_2.1.txt", "ReadMe", "Download")</li>
        </ul>
    </div>
</div>